services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: false
    envVars:
      - key: DB_HOST
        value: your_db_host
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_NAME
        value: your_db_name
